version: "3.9"

x-defaults: &x-defaults
  image: local
  build: .
  stdin_open: true
  tty: true
  restart: always
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - "./:/project/code"
  depends_on:
    - postgres
    - rabbitmq
    - memcached

services:

  backend:
    command: python ./app/manage.py runserver 0.0.0.0:8000
    container_name: backend
    <<: *x-defaults

  celery:
    command: celery -A settings worker -l info --pool threads -c 10 --pidfile=/tmp/celery.pid
    container_name: celery
    <<: *x-defaults

  celerybeat:
    command: celery -A settings beat -l info --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
    container_name: celerybeat
    <<: *x-defaults


  flower:
    command: celery -A tasks flower
    container_name: flower
    <<: *x-defaults


  memcached:
    image: memcached:1.6.12
    container_name: memcached
#    ports:
#      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.9.12-management-alpine
    container_name: rabbitmq
    env_file: .env
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file: .env
#    ports:
#      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env

#
#  nginx:
#    image: nginx
#    container_name: nginx
#    depends_on:
#      - backend
#    ports:
#      - "80:80"
#    volumes:
#      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  db_data: {}
