# Generated by Django 3.2.7 on 2021-11-30 12:55
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0007_source_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='code_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
